# pylint: disable=no-member
"""
base

Revision ID: 820d274e5095
Revises:
Create Date: 2021-11-13 03:36:38.343078

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "820d274e5095"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "circuits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_circuits_code"), "circuits", ["code"], unique=False)
    op.create_index(op.f("ix_circuits_country"), "circuits", ["country"], unique=False)
    op.create_index(op.f("ix_circuits_id"), "circuits", ["id"], unique=False)
    op.create_index(op.f("ix_circuits_location"), "circuits", ["location"], unique=False)
    op.create_index(op.f("ix_circuits_name"), "circuits", ["name"], unique=False)
    op.create_index(op.f("ix_circuits_url"), "circuits", ["url"], unique=False)
    op.create_table(
        "constructors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nationality", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_constructors_code"), "constructors", ["code"], unique=False)
    op.create_index(op.f("ix_constructors_id"), "constructors", ["id"], unique=False)
    op.create_index(op.f("ix_constructors_name"), "constructors", ["name"], unique=False)
    op.create_index(
        op.f("ix_constructors_nationality"), "constructors", ["nationality"], unique=False
    )
    op.create_index(op.f("ix_constructors_url"), "constructors", ["url"], unique=False)
    op.create_table(
        "drivers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("acronym", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name_first", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name_last", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=False),
        sa.Column("nationality", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drivers_acronym"), "drivers", ["acronym"], unique=False)
    op.create_index(op.f("ix_drivers_code"), "drivers", ["code"], unique=False)
    op.create_index(op.f("ix_drivers_dob"), "drivers", ["dob"], unique=False)
    op.create_index(op.f("ix_drivers_id"), "drivers", ["id"], unique=False)
    op.create_index(op.f("ix_drivers_name_first"), "drivers", ["name_first"], unique=False)
    op.create_index(op.f("ix_drivers_name_last"), "drivers", ["name_last"], unique=False)
    op.create_index(op.f("ix_drivers_nationality"), "drivers", ["nationality"], unique=False)
    op.create_index(op.f("ix_drivers_number"), "drivers", ["number"], unique=False)
    op.create_index(op.f("ix_drivers_url"), "drivers", ["url"], unique=False)
    op.create_table(
        "races",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("circuit_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["circuit_id"],
            ["circuits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_races_circuit_id"), "races", ["circuit_id"], unique=False)
    op.create_index(op.f("ix_races_id"), "races", ["id"], unique=False)
    op.create_index(op.f("ix_races_name"), "races", ["name"], unique=False)
    op.create_index(op.f("ix_races_round"), "races", ["round"], unique=False)
    op.create_index(op.f("ix_races_start"), "races", ["start"], unique=False)
    op.create_index(op.f("ix_races_url"), "races", ["url"], unique=False)
    op.create_index(op.f("ix_races_year"), "races", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_races_year"), table_name="races")
    op.drop_index(op.f("ix_races_url"), table_name="races")
    op.drop_index(op.f("ix_races_start"), table_name="races")
    op.drop_index(op.f("ix_races_round"), table_name="races")
    op.drop_index(op.f("ix_races_name"), table_name="races")
    op.drop_index(op.f("ix_races_id"), table_name="races")
    op.drop_index(op.f("ix_races_circuit_id"), table_name="races")
    op.drop_table("races")
    op.drop_index(op.f("ix_drivers_url"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_number"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_nationality"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_name_last"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_name_first"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_id"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_dob"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_code"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_acronym"), table_name="drivers")
    op.drop_table("drivers")
    op.drop_index(op.f("ix_constructors_url"), table_name="constructors")
    op.drop_index(op.f("ix_constructors_nationality"), table_name="constructors")
    op.drop_index(op.f("ix_constructors_name"), table_name="constructors")
    op.drop_index(op.f("ix_constructors_id"), table_name="constructors")
    op.drop_index(op.f("ix_constructors_code"), table_name="constructors")
    op.drop_table("constructors")
    op.drop_index(op.f("ix_circuits_url"), table_name="circuits")
    op.drop_index(op.f("ix_circuits_name"), table_name="circuits")
    op.drop_index(op.f("ix_circuits_location"), table_name="circuits")
    op.drop_index(op.f("ix_circuits_id"), table_name="circuits")
    op.drop_index(op.f("ix_circuits_country"), table_name="circuits")
    op.drop_index(op.f("ix_circuits_code"), table_name="circuits")
    op.drop_table("circuits")
    # ### end Alembic commands ###
