# pylint: disable=no-member
"""
add altitude to circuits

Revision ID: eb4faca60b62
Revises: 820d274e5095
Create Date: 2021-11-13 17:06:34.758736

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "eb4faca60b62"
down_revision = "820d274e5095"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("circuits", sa.Column("altitude", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_circuits_altitude"), "circuits", ["altitude"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_circuits_altitude"), table_name="circuits")
    op.drop_column("circuits", "altitude")
    # ### end Alembic commands ###
