# pylint: disable=no-member
"""
laps table

Revision ID: f64fa8d2dc82
Revises: 38efedfeb062
Create Date: 2021-11-14 02:56:30.976591

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "f64fa8d2dc82"
down_revision = "38efedfeb062"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "laps",
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("lap", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("time", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.PrimaryKeyConstraint("race_id", "driver_id"),
    )
    op.create_index(op.f("ix_laps_driver_id"), "laps", ["driver_id"], unique=False)
    op.create_index(op.f("ix_laps_lap"), "laps", ["lap"], unique=False)
    op.create_index(op.f("ix_laps_position"), "laps", ["position"], unique=False)
    op.create_index(op.f("ix_laps_race_id"), "laps", ["race_id"], unique=False)
    op.create_index(op.f("ix_laps_time"), "laps", ["time"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_laps_time"), table_name="laps")
    op.drop_index(op.f("ix_laps_race_id"), table_name="laps")
    op.drop_index(op.f("ix_laps_position"), table_name="laps")
    op.drop_index(op.f("ix_laps_lap"), table_name="laps")
    op.drop_index(op.f("ix_laps_driver_id"), table_name="laps")
    op.drop_table("laps")
    # ### end Alembic commands ###
